apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: security-playbook
  namespace: appsec
  labels:
    team: appsec
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: "{{ image }}"
  port: 8080
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 32Mi
  ingresses:
    - https://sikkerhet.nav.no/
  replicas:
    cpuThresholdPercentage: 90
    max: 2
    min: 2
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  observability:
    logging:
      destinations:
        - id: loki
