apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: security-playbook
  namespace: security-champion-admin
  labels:
    team: security-champion-admin
spec:
  port: 8080
  ingresses:
    {{#each ingresses as |url|}}
       - {{url}}
      {{/each}}
  image: {{ image }}
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 200Mi
  liveness:
    path: /internal/isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 3
  readiness:
    path: /internal/isready
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: false

