const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { test } = require("node:test");
const generateSidebar = require("./secure-development-sidebar");

const topicIds = fs
  .readdirSync(path.join(__dirname, "../docs/08-sikker-utvikling"))
  .filter(
    (name) =>
      /\.(md|mdx)$/.test(name) && name !== "index.md" && !name.startsWith("_"),
  )
  .map((name) => `sikker-utvikling/${name.replace(/\.(md|mdx)$/, "")}`);

function topic(id) {
  return { type: "doc", id };
}

function secureDevelopment(items = topicIds.map(topic)) {
  return {
    type: "category",
    label: "Sikker utvikling i Nav IT 🔒",
    link: { type: "doc", id: "sikker-utvikling/index" },
    items,
  };
}

function generate(items) {
  return generateSidebar({
    item: { type: "autogenerated", dirName: "." },
    defaultSidebarItemsGenerator: () => items,
  });
}

test("all topics appear exactly once in the intended category and reading order", async () => {
  const original = secureDevelopment();
  const snapshot = structuredClone(original);
  const [result] = await generate([original]);
  assert.deepEqual(original, snapshot);
  assert.deepEqual(result.link, original.link);
  assert.equal(result.label, original.label);
  assert.deepEqual(
    result.items.map(({ label, items }) => [
      label,
      items.map(({ id }) => id.replace("sikker-utvikling/", "")),
    ]),
    [
      ["Risiko", ["trusselmodellering", "tryggnok", "beredskap"]],
      [
        "Utviklermiljø",
        [
          "klientsikkerhet",
          "seopoisoning",
          "ki",
          "tredjepartskode",
          "supply-chain",
        ],
      ],
      ["Bygg og drift", ["github", "baseimages", "containere", "webapp"]],
      ["Tilgang", ["tilgangsstyring", "hemmeligheter", "m2m"]],
      ["App-sikkerhet", ["inputvalidering", "filopplasting", "ddos"]],
      [
        "Logging",
        ["logging", "oppslagslogg", "auditlogg_db_endring", "juridisk_logg"],
      ],
      ["Testing", ["kodeanalyse", "dynamiskanalyse", "pentesting"]],
    ],
  );
  const groupedIds = result.items.flatMap(({ items }) =>
    items.map(({ id }) => id),
  );
  assert.deepEqual([...groupedIds].sort(), [...topicIds].sort());
  assert.equal(new Set(groupedIds).size, groupedIds.length);
  assert.equal(
    new Set(result.items.map((item) => item.customProps.overviewId)).size,
    7,
  );
  for (const category of result.items) {
    assert.ok(category.label.length <= 13);
    assert.equal(category.collapsed, true);
    assert.equal(category.collapsible, true);
    assert.ok(category.description);
    for (const item of category.items) {
      assert.equal(
        item,
        original.items.find(({ id }) => id === item.id),
      );
    }
  }
});

test("other sidebar sections and document metadata are preserved", async () => {
  const other = {
    type: "category",
    label: "Verktøy",
    items: [topic("verktoy/index")],
  };
  const topics = topicIds.map(topic);
  topics[0] = {
    ...topics[0],
    label: "Custom label",
    customProps: { example: true },
  };
  const input = [topic("index"), other, secureDevelopment(topics)];
  const result = await generate(input);
  assert.deepEqual(result.slice(0, 2), input.slice(0, 2));
  assert.ok(result[2].items.flatMap(({ items }) => items).includes(topics[0]));
});

test("nested secure development sections are grouped", async () => {
  const [result] = await generate([
    { type: "category", label: "Parent", items: [secureDevelopment()] },
  ]);
  assert.equal(result.items[0].items.length, 7);
});

test("new topics cannot silently disappear from navigation", async () => {
  await assert.rejects(
    generate([
      secureDevelopment([
        ...topicIds.map(topic),
        topic("sikker-utvikling/new"),
      ]),
    ]),
    /Uncategorized secure development topics: sikker-utvikling\/new/,
  );
});

test("deleted or renamed topics require updating the category definition", async () => {
  await assert.rejects(
    generate([
      secureDevelopment(
        topicIds.filter((id) => id !== "sikker-utvikling/ki").map(topic),
      ),
    ]),
    /Missing or duplicate secure development topic: sikker-utvikling\/ki/,
  );
});

test("duplicate topics and unexpected nested categories are rejected", async () => {
  await assert.rejects(
    generate([
      secureDevelopment([...topicIds.map(topic), topic("sikker-utvikling/ki")]),
    ]),
    /Duplicate secure development topic: sikker-utvikling\/ki/,
  );
  await assert.rejects(
    generate([
      secureDevelopment([
        ...topicIds.map(topic),
        { type: "category", label: "Unexpected", items: [] },
      ]),
    ]),
    /Secure development topics must be document sidebar items/,
  );
});
