name: Build and deploy main
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    environment: prod
    concurrency:
      group: deploy-prod
      cancel-in-progress: false # Let in-flight deploys finish
    timeout-minutes: 15
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5 # v0
        id: docker-push
        with:
          team: appsec
          push_image: true
          pull: true
      - uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
